package testlib

/*
#include <linux/netlink.h>
*/
import "C"

const (
	NLMSG_NOOP	= C.NLMSG_NOOP
	NLMSG_ERROR	= C.NLMSG_ERROR
	NLMSG_DONE	= C.NLMSG_DONE
	NLMSG_OVERRUN	= C.NLMSG_OVERRUN
	NLMSG_MIN_TYPE	= C.NLMSG_MIN_TYPE
)

const (
	NLM_F_REQUEST	= C.NLM_F_REQUEST
	NLM_F_MULTI	= C.NLM_F_MULTI
	NLM_F_ACK	= C.NLM_F_ACK
	NLM_F_ECHO	= C.NLM_F_ECHO
	NLM_F_DUMP_INTR	= C.NLM_F_DUMP_INTR
)

const (
	NLA_F_NESTED	= C.NLA_F_NESTED
)

const (
	NETLINK_NETFILTER	= C.NETLINK_NETFILTER
	NETLINK_BROADCAST_ERROR	= C.NETLINK_BROADCAST_ERROR
)
